from enum import Enum


class e_rotors(Enum):
    """
    I = EKMFLGDQVZNTOWYHXUSPAIBRCJ, Q |
    II = AJDKSIRUXBLHWTMCQGZNPYFVOE, E |
    III = BDFHJLCPRTXVZNYEIWGAKMUSQO, V |
    IV = ESOVPZJAYQUIRHXLNFTGKDCMWB, J |
    V = VZBRGITYUPSDNHLXAWMJQOFECK, Z
    """

    I = ("EKMFLGDQVZNTOWYHXUSPAIBRCJ", "Q")
    II = ("AJDKSIRUXBLHWTMCQGZNPYFVOE", "E")
    III = ("BDFHJLCPRTXVZNYEIWGAKMUSQO", "V")
    IV = ("ESOVPZJAYQUIRHXLNFTGKDCMWB", "J")
    V = ("VZBRGITYUPSDNHLXAWMJQOFECK", "Z")
